# Generated by Django 5.0 on 2026-09-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Auditoriya nomi')),
                ('capacity', models.IntegerField(verbose_name="Sig'im")),
            ],
            options={
                'verbose_name': 'Auditoriya',
                'verbose_name_plural': 'Auditoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Fan kodi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('degree', models.CharField(choices=[('professor', 'Professor'), ('dotsent', 'Dotsent'), ('katta_oqituvchi', "Katta o'qituvchi"), ('assistent', 'Assistent')], max_length=20, verbose_name='Daraja')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Superadmin')),
                ('max_daily_hours', models.IntegerField(default=4, verbose_name='Kunlik maksimal soat')),
                ('rest_hours_required', models.IntegerField(default=1, verbose_name='Tanaffus soatlari (har N paradan keyin)')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('lesson_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('seminar', 'Seminar')], max_length=10, verbose_name='Dars turi')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni')),
                ('pair_number', models.IntegerField(verbose_name='Para raqami (1-5)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.room', verbose_name='Auditoriya')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Jadval sloti',
                'verbose_name_plural': 'Jadval slotlari',
            },
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('lecture_hours_per_week', models.IntegerField(default=2, verbose_name="Ma'ruza soatlari (haftada)")),
                ('seminar_hours_per_week', models.IntegerField(default=2, verbose_name='Seminar soatlari (haftada)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'quv rejasi",
                'verbose_name_plural': "O'quv rejalari",
                'unique_together': {('subject', 'teacher', 'group_name')},
            },
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week', 'pair_number'), name='unique_teacher_time_slot', violation_error_message="O'qituvchi bir vaqtda ikkita darsda bo'la olmaydi"),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('group_name', 'day_of_week', 'pair_number'), name='unique_group_time_slot', violation_error_message="Guruh bir vaqtda ikkita darsda bo'la olmaydi"),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('room', 'day_of_week', 'pair_number'), name='unique_room_time_slot', violation_error_message="Auditoriya bir vaqtda ikkita darsda bo'la olmaydi"),
        ),
    ]
