# Generated by Django 5.0 on 2026-09-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rest_hours_required',
            field=models.IntegerField(default=1, verbose_name='Tanaffus soatlari (har 3 paradan keyin 1 para)'),
        ),
    ]
