# Generated by Django 5.0 on 2026-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_teacher_rest_hours_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='stavka',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Stavka (1 stavka = 20 soat/hafta)'),
        ),
    ]
