# Generated by Django 5.0 on 2026-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_teacher_stavka'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_stavka', models.IntegerField(default=20, verbose_name='1 stavkada soatlar soni')),
            ],
            options={
                'verbose_name': 'Tizim sozlamalari',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
    ]
