# Generated by Django 5.0 on 2026-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_groups',
            field=models.TextField(blank=True, help_text='Ruxsat etilgan guruhlar (vergul bilan ajratilgan)', verbose_name='Ruxsat etilgan guruhlar'),
        ),
    ]
