# Generated by Django 5.0 on 2026-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_systemsettings_allowed_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Fan kodi'),
        ),
    ]
