# Generated by Django 5.0 on 2026-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], db_index=True, verbose_name='Hafta kuni'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='group_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Guruh nomi'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='pair_number',
            field=models.IntegerField(db_index=True, verbose_name='Para raqami (1-5)'),
        ),
    ]
